[package]
name = "rust-exp-fst"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
fst = { version = "0.4", features = ["levenshtein"] }
memmap2 = "0.9.9"
ratatui = "0.30.0"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "benchmark"
harness = false
